/* ============================================================
   Password — offline fallback content.
   Used when words.json cannot be fetched (e.g. the page is
   opened straight from disk, or GitHub Pages is unreachable).
   Generated from words.json — tests/pwd-core.test.mjs asserts the
   two files hold identical games, so regenerate both together.
   ============================================================ */

"use strict";

const PWD_DEFAULT_GAME = {
  "title": "Password — Game Night",
  "settings": {
    "currency": "$",
    "targetScore": 25,
    "startValue": 10,
    "lightningSeconds": 60,
    "lightningWords": 5,
    "lightningValue": 100,
    "allFiveBonus": true,
    "swapRoles": true
  },
  "words": [
    "Umbrella",
    "Whisper",
    "Mountain",
    "Ticket",
    "Jealous",
    "Lantern",
    "Bounce",
    "Courage",
    "Pancake",
    "Slippery",
    "Anchor",
    "Gossip",
    "Feather",
    "Stumble",
    "Ancient",
    "Bicycle",
    "Puddle",
    "Rescue",
    "Grumpy",
    "Harbor",
    "Blanket",
    "Sneeze",
    "Mystery",
    "Crispy",
    "Candle",
    "Wander",
    "Shadow",
    "Fragile",
    "Compass",
    "Giggle",
    "Holiday",
    "Prickly",
    "Cottage",
    "Juggle",
    "Silence",
    "Dizzy",
    "Curtain",
    "Scatter",
    "Victory",
    "Fluffy",
    "Dolphin",
    "Sparkle",
    "Rumor",
    "Awkward",
    "Elbow",
    "Tumble",
    "Patience",
    "Hollow",
    "Garden",
    "Freeze",
    "Legend",
    "Stubborn",
    "Igloo",
    "Confess",
    "Journey",
    "Salty",
    "Jacket",
    "Nibble",
    "Fortune",
    "Spooky",
    "Kettle",
    "Explore",
    "Riddle",
    "Curious",
    "Ladder",
    "Shiver",
    "Trouble",
    "Gigantic",
    "Marble",
    "Gallop",
    "Wisdom",
    "Clumsy",
    "Mitten",
    "Persuade",
    "Panic",
    "Elegant",
    "Napkin",
    "Devour",
    "Promise",
    "Sneaky",
    "Orchard",
    "Rehearse",
    "Danger",
    "Wobbly",
    "Pebble",
    "Applaud",
    "Rhythm",
    "Icy",
    "Pillow",
    "Collide",
    "Talent",
    "Chilly",
    "Ribbon",
    "Grumble",
    "Destiny",
    "Graceful",
    "Saddle",
    "Linger",
    "Nonsense",
    "Mighty",
    "Shovel",
    "Migrate",
    "Peace",
    "Thirsty",
    "Sponge",
    "Fidget",
    "Surprise",
    "Loyal",
    "Squirrel",
    "Bargain",
    "Memory",
    "Tangled",
    "Stadium",
    "Forgive",
    "Justice",
    "Humble",
    "Tunnel",
    "Ponder",
    "Laughter",
    "Noisy",
    "Violin",
    "Dazzle",
    "Kindness",
    "Peculiar",
    "Waffle",
    "Rummage",
    "Gravity",
    "Playful",
    "Whistle",
    "Blink",
    "Honesty",
    "Rusty",
    "Window",
    "Sprint",
    "Wonder",
    "Drowsy",
    "Zipper",
    "Scribble",
    "Secret",
    "Sturdy",
    "Balloon",
    "Yawn",
    "Suspense",
    "Eager",
    "Basket",
    "Tiptoe",
    "Freedom",
    "Soggy",
    "Bridge",
    "Haggle",
    "Luck",
    "Fearless",
    "Bucket",
    "Squeeze",
    "Tradition",
    "Shiny",
    "Button",
    "Mumble",
    "Curiosity",
    "Brittle",
    "Camera",
    "Deliver",
    "Trust",
    "Polite",
    "Carpet",
    "Invent",
    "Confusion",
    "Cozy",
    "Chimney",
    "Inhale",
    "Parade",
    "Generous",
    "Clover",
    "Pounce",
    "Rainbow",
    "Bumpy",
    "Cactus",
    "Celebrate",
    "Sunset",
    "Jolly",
    "Drawer",
    "Flatter",
    "Thunder",
    "Silky",
    "Envelope",
    "Snore",
    "Volcano",
    "Nervous",
    "Fossil",
    "Borrow",
    "Glacier",
    "Speedy",
    "Hammock",
    "Shuffle",
    "Helmet",
    "Tidy",
    "Jungle",
    "Wobble",
    "Lighthouse",
    "Marvelous"
  ]
};

if (typeof module === "object" && module.exports) module.exports = PWD_DEFAULT_GAME;
if (typeof globalThis !== "undefined") globalThis.PWD_DEFAULT_GAME = PWD_DEFAULT_GAME;
